% -------------------------------------------------------------------------
%       Acoustic wave equation finite diference simulator
% -------------------------------------------------------------------------
% Design an example showing that Mie scattering produces attenuation
% Suggestion: build an uniform medium, insert a source in the center of 
% the model and 2 eceivers, one on the left and one 
% on the right of the source, simmetrically.
% Now, on one of the 2 sides of the source, add to the velocity model
% random variations (zero mean, anomalies below wavelength) and
% verify on the seismic traces that the wavefront crossing the "noisy" zone
% is more attenuated

clear all;  
clc;

% Define Model Parameters
Nx = 801;
Nz = 401;
x = linspace(0, 2400, Nx); % dx = 3 (m)
z = linspace(0, 1200, Nz); % dz = 3 (m)
[X, Z] = meshgrid(x, z);
vel = 1500 * ones(size(X)); % size of vel matrix 801 * 401. Meduim has a 1500 velocity

% Add random variations in velocity on left side of the source
noisy_zone = X <= 1200;
vel(noisy_zone) = vel(noisy_zone) + 350 * randn(size(vel(noisy_zone))); % size(vel(noisy_zone) = 160801, rand(...) = 160801 number between zero and one, The velocity ofvaries as much as 350

%U = rand(size(X1));
%gaussian_noise = 300 * norminv(U, 0, 1);
%vel(noisy_zone) = vel(noisy_zone) + gaussian_noise(noisy_zone);

model.x = x;
model.z = z;
model.vel = vel;

% Define source and receivers
% seicmic wave transmits from src and interacts with anomalies
source.x = [1200]; % Source in the center
source.z = [600];  % Depth of the source
source.f0 = [10];  % Frequency of the source, increase f0 leads to decrease wavelenght and waves plot becomes more More oscillating and more compact
source.t0 = [0.03];  % Time of source emission starting
source.type = [1];  % Ricker wavelet
source.amp = [8];   % Amplitude of the wave that generated by the source

% Define receivers on both sides of the source
model.recx=[300 2100];
model.recz=[600 600];
model.dtrec = 0.002; % In each 0.002s, one sample from waves data are record

simul.timeMax = 0.9;
simul.borderAlg = 1; % enable absorbing boundaries
simul.printRatio = 5; % Snapshots of wave propagation are displayed every 5 computation steps
simul.higVal = 0.5; % Color scale range
simul.lowVal = 0.1;
simul.bkgVel = 1; % Overlay the velocity model in simulation images
simul.cmap = 'turbo';

% Run the simulation wich resulting seismic traces
recfield = acu2Dpro(model, source, simul);

% Plot the seismic traces
figure;
time = recfield.time;
traces = recfield.data;
%plot(time, traces, 'LineWidth', 1.5);
plot(time, traces(:,1), 'r-', 'LineWidth', 1.5);
hold on;
plot(time, traces(:,2), 'g-', 'LineWidth', 1.5);
xlabel('Time (s)', 'FontSize', 12, 'FontWeight', 'bold');
ylabel('Amplitude', 'FontSize', 12, 'FontWeight', 'bold');
title('Seismic Traces with Mie Scattering', 'FontSize', 14, 'FontWeight', 'bold');
legend({'Receiver Left', 'Receiver Right'}, 'FontSize', 10, 'Location', 'northwest');
grid on;
axis tight;
set(gca, 'FontSize', 12);

% Plot 2: Seismic Traces in Subplots
figure;
for i = 1:length(model.recx)
    subplot(length(model.recx), 1, i);
    plot(time, traces(:,i), 'LineWidth', 1.5);
    xlabel('Time (s)', 'FontSize', 10, 'FontWeight', 'bold');
    ylabel('Amplitude', 'FontSize', 10, 'FontWeight', 'bold');
    title(['Seismic Trace - Receiver ', num2str(i)], 'FontSize', 12, 'FontWeight', 'bold');
    grid on;
end

% 2D Visualization of Velocity Model
figure;
imagesc(model.x, model.z, model.vel);
colormap(parula);
colorbar;
hold on
xlabel('X Position (m)', 'FontSize', 12, 'FontWeight', 'bold');
ylabel('Z Depth (m)', 'FontSize', 12, 'FontWeight', 'bold');
title('Velocity Model with Mie Scattering Zone', 'FontSize', 14, 'FontWeight', 'bold');
set(gca, 'YDir', 'normal', 'FontSize', 12);

% 3D Surface Plot of Velocity Model
figure;
surf(model.x, model.z, model.vel, 'EdgeColor', 'none');
colormap(turbo);
colorbar;
lighting phong;
camlight headlight;
xlabel('X Position (m)', 'FontSize', 12, 'FontWeight', 'bold');
ylabel('Z Depth (m)', 'FontSize', 12, 'FontWeight', 'bold');
zlabel('Velocity (m/s)', 'FontSize', 12, 'FontWeight', 'bold');
title('3D Surface of Velocity Model', 'FontSize', 14, 'FontWeight', 'bold');
view(3);
set(gca, 'FontSize', 12);
